#!/usr/bin/perl
########################################################################
#
# $Id$
#
# Copyright (c) 2004 Okunev Igor <gosha@prv.mts-nn.ru>
#
########################################################################

my $r = '
	(\\S+)						# Host
		\\s
	(\\S+)						# Login
		\\s
	(\\S+)						# User
		\\s
		\\[
	(							# date
		(
			(\\d{2})			# date_day
					/
			(\\w+)				# date_mon
					/
			(\\d{4})			# date_year
		)
			:
		(
			(\\d{2})			# time_hour
					:
			(\\d{2})			# time_min
					:
			(\\d{2})			# time_sec
		)
			\\s+[^\]]*?
	)
		\\]
		\\s\\"
	(\\w+)						# method
		\\s
	(							# request
	
		(?:/~([^/]+))?			# req_user
		
		(						# req_path
			(?:[^?\s]+)?
			/
		)

		(						# req_name
			[^?/]+?
			(?:\.([^.?/]+))?	# req_ext
		)?
		
		(?:\?(\\S*))?			# req_qstring
	)
		\\s
	(\\w+\\/\\d+\\.\\d+)		# proto
		"
		\\s
	(\\d+)						# lstatus
		\\s
	(\\d+|-)					# byte
';
